# Generated by Django 4.2.1 on 2023-05-29 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='casilla',
            name='costo',
        ),
        migrations.AddField(
            model_name='alquilercasillas',
            name='tipo_alquiler',
            field=models.CharField(choices=[('M', 'Mensual'), ('S', 'Semanal'), ('A', 'Anual')], default='M', max_length=1),
        ),
        migrations.CreateModel(
            name='Precio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio_mensual', models.DecimalField(decimal_places=2, max_digits=10)),
                ('precio_semanal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('precio_anual', models.DecimalField(decimal_places=2, max_digits=10)),
                ('casilla', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.casilla')),
            ],
        ),
    ]
